sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
    
  rabbitmq:
    host: 192.168.171.131
    port: 5672
    username: admin
    password: admin   
      
server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#使用 ip 地址注册,而不是localhost或主机名注册
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}      
   
management:
  endpoints:
    web:
      exposure:
        include: refresh